name: Periodic Health Check

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check deployed URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://lit-cove-71604.herokuapp.com/healthcheck|https://lit-cove-71604.herokuapp.com/
          max-attempts: 3
          retry-delay: 5s